//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarMake
    {
        public CarMake()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int Make_Id { get; set; }
        public string Make { get; set; }
        public Nullable<int> Country_Id { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual Country Country { get; set; }
    }
}
